version: '3.8'

services:
  # Наследуем только базовые сервисы из главного compose.yaml
  postgres:
    extends:
      file: compose.yaml
      service: postgres

  whisper:
    extends:
      file: compose.yaml
      service: whisper

volumes:
  pgdata: 