version: '3.8'

services:
  # Наследуем только базовые сервисы из главного compose.yaml
  postgres:
    extends:
      file: compose.yaml
      service: postgres

  # ElevenLabs работает как SaaS, не требует локального контейнера

volumes:
  pgdata: 