spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hr_recruiter
    username: hr_user
    password: hr_password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
logging:
  level:
    azhukov: INFO 