spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hr_recruiter
  data:
    redis:
      host: redis
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
logging:
  level:
    azhukov: INFO 