spring:
  application:
    name: hr-recruiter-backend
  
  # Multipart Configuration для аудио файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
      resolve-lazily: false
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_recruiter
    username: hr_user
    password: hr_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@example.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Spring AI Configuration
  ai:
    openai:
      api-key: ${OPEAN_AI_API_KEY:}
      transcription:
        api-key: ${OPEAN_AI_API_KEY:}
      base-url: https://api.openai.com
      audio:
        transcription:
          model: whisper-1
          language: ru
          response-format: json

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: UTC

# Logging Configuration
logging:
  level:
    azhukov: INFO
    azhukov.config.LoggingConfig: INFO
    azhukov.service.ai.elevenlabs: DEBUG
    azhukov.config.ElevenLabsConfig: DEBUG
    azhukov.config.ElevenLabsProperties: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/hr-recruiter.log
    max-size: 10MB
    max-history: 30

# Security Configuration
security:
  jwt:
    secret: your-secret-key-here-change-in-production
    expiration: 86400000 # 24 hours in milliseconds
  basic:
    enabled: true



# OpenRouter AI Configuration (основной AI сервис)
openrouter:
  api:
    key: ${OPENROUTER_API_KEY:sk-or-demo-key}
    url: https://openrouter.ai/api/v1/chat/completions
  model: anthropic/claude-sonnet-4-20250522
  max-tokens: 1000
  temperature: 0.7
  timeout: 30000
  max-retries: 3
  retry-delay: 1000
  enable-prompt-caching: true
  prompt-cache-size: 1000
  enable-request-logging: true
  enable-usage-metrics: true

# Application Properties
app:
  debug:
    enabled: false # Включить для логирования тела запросов
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  file:
    upload:
      max-size: 10MB
      allowed-types: jpg,jpeg,png,gif,pdf,doc,docx
      upload-dir: uploads
  
  cache:
    ttl:
      default: 3600 # 1 hour
      user: 1800 # 30 minutes
      position: 7200 # 2 hours
      question: 7200 # 2 hours
  
  ai:
    transcription:
      # ElevenLabs STT Configuration
      elevenlabs:
        api-url: https://api.elevenlabs.io
        api-key: ${ELEVEN_LABS_API_KEY:}
        timeout: 60000
        retry-attempts: 3
        model-id: ELEVEN_MULTILINGUAL_V2
        language: RUSSIAN
        temperature: 0.0
      provider: OPENAI # или ELEVENLABS

# Transcription Configuration
transcription:
  provider: ELEVENLABS

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true